<?php

return [
    [
        'name' => 'status',
        'title' => '状态',
        'type' => 'bool',
        'content' => [
            1 => '启用',
            0 => '禁用',
        ],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'overtime',
        'title' => '超时时间(分钟)',
        'type' => 'number',
        'content' => [],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '单规定时间内无任何操作则视为超时',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'password',
        'title' => '恢复密码',
        'type' => 'bool',
        'content' => [
            1 => '启用',
            0 => '禁用',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '恢复时是否需要密码',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'failure_retry',
        'title' => '失败次数',
        'type' => 'number',
        'content' => [],
        'value' => '3',
        'rule' => 'required',
        'msg' => '',
        'tip' => '超过后将强制退出登录,为0时不启用',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'debug',
        'title' => '调试模式',
        'type' => 'bool',
        'content' => [
            1 => '开启',
            0 => '关闭',
        ],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '关闭调试模式后,打开浏览器调试将自动锁定页面,恢复密码启用后有效',
        'ok' => '',
        'extend' => '',
    ],
];
