<?php

return [
    [
        'name' => 'is_default',
        'title' => '接管弹窗',
        'type' => 'radio',
        'content' => [
            1 => '官方弹窗',
            2 => '插件弹窗',
        ],
        'value' => '2',
        'rule' => 'required',
        'msg' => '',
        'tip' => '图片选择时，官方默认弹窗，插件弹窗方式，这两种方式。',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'is_compress',
        'title' => '开启压缩',
        'type' => 'radio',
        'content' => [
            1 => '开启',
            0 => '关闭',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'compress_scale',
        'title' => '压缩比例',
        'type' => 'select',
        'content' => [
            '1' => '1.0',
            '0.9' => '0.9',
            '0.8' => '0.8',
            '0.7' => '0.7',
            '0.6' => '0.6',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => '__tips__',
        'title' => '温馨提示',
        'type' => '',
        'content' => [],
        'value' => '压缩比例：建议使用1.0,原比例无损压缩。<br/>第三方云存储插件，上传模式设置<span style="color:red">【服务器中转】</span>压缩才有效。',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => 'alert-info-light',
    ],
];
