<?php
/**
 * 菜单配置文件
 */

return [
    [
        'type' => 'file',
        'name' => 'equipment',
        'title' => '设备管理',
        'icon' => 'fa fa-microchip',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'sublist' => [
            [
                'type' => 'file',
                'name' => 'equipment/dashboard/index',
                'title' => '看板中心',
                'icon' => 'fa fa-tachometer',
                'condition' => '',
                'remark' => '',
                'ismenu' => 1,
            ],
            [
                'type' => 'file',
                'name' => 'equipment/department',
                'title' => '部门管理',
                'icon' => 'fa fa-users',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'sublist' => [
                    [
                        'type' => 'file',
                        'name' => 'equipment/department/index',
                        'title' => '查看',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/department/add',
                        'title' => '添加',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/department/edit',
                        'title' => '编辑',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/department/del',
                        'title' => '删除',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/department/multi',
                        'title' => '批量更新',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/department/recyclebin',
                        'title' => '回收站',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/department/restore',
                        'title' => '回收站-还原',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/department/destroy',
                        'title' => '回收站-销毁',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                ],
            ],
            [
                'type' => 'file',
                'name' => 'equipment/staff',
                'title' => '员工管理',
                'icon' => 'fa fa-user-circle',
                'condition' => '',
                'remark' => '',
                'ismenu' => 1,
                'sublist' => [
                    [
                        'type' => 'file',
                        'name' => 'equipment/staff/index',
                        'title' => '查看',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/staff/add',
                        'title' => '添加',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/staff/edit',
                        'title' => '编辑',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/staff/del',
                        'title' => '删除',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/staff/multi',
                        'title' => '批量更新',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/staff/picker',
                        'title' => '员工选择弹窗(务必√)',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/staff/pickerDeal',
                        'title' => '员工选择弹窗确认(务必√)',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/staff/getPlanSelectpage',
                        'title' => '选择员工(务必√)',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/staff/unbind',
                        'title' => '解绑微信小程序',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/staff/recyclebin',
                        'title' => '回收站',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/staff/restore',
                        'title' => '回收站-还原',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/staff/destroy',
                        'title' => '回收站-销毁',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                ],
            ],
            [
                'type' => 'file',
                'name' => 'equipment/supplier',
                'title' => '供应商管理',
                'icon' => 'fa fa-handshake-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 1,
                'sublist' => [
                    [
                        'type' => 'file',
                        'name' => 'equipment/supplier/index',
                        'title' => '查看',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/supplier/add',
                        'title' => '添加',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/supplier/edit',
                        'title' => '编辑',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/supplier/del',
                        'title' => '删除',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/supplier/multi',
                        'title' => '批量更新',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/supplier/recyclebin',
                        'title' => '回收站',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/supplier/restore',
                        'title' => '回收站-还原',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/supplier/destroy',
                        'title' => '回收站-销毁',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                ],
            ],
            [
                'type' => 'file',
                'name' => 'equipment/archive',
                'title' => '设备档案',
                'icon' => 'fa fa-archive',
                'condition' => '',
                'remark' => '',
                'ismenu' => 1,
                'sublist' => [
                    [
                        'type' => 'file',
                        'name' => 'equipment/archive/import',
                        'title' => '导入',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/archive/index',
                        'title' => '查看',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/archive/add',
                        'title' => '添加',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/archive/edit',
                        'title' => '编辑',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/archive/del',
                        'title' => '删除',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/archive/multi',
                        'title' => '批量更新',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/archive/exportTag',
                        'title' => '导出标签数据',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                ],
            ],
            [
                'type' => 'file',
                'name' => 'equipment/equipment',
                'title' => '设备列表',
                'icon' => 'fa fa-list',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'sublist' => [
                    [
                        'type' => 'file',
                        'name' => 'equipment/equipment/index',
                        'title' => '查看',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/equipment/del',
                        'title' => '删除',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/equipment/qrcode',
                        'title' => '二维码标签',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                ],
            ],
            [
                'type' => 'file',
                'name' => 'equipment/inspection',
                'title' => '巡检计划',
                'icon' => 'fa fa-recycle',
                'condition' => '',
                'remark' => '',
                'ismenu' => 1,
                'sublist' => [
                    [
                        'type' => 'file',
                        'name' => 'equipment/inspection/index',
                        'title' => '查看',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/inspection/add',
                        'title' => '添加',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/inspection/deactivated',
                        'title' => '已停用计划',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                ],
            ],
            [
                'type' => 'file',
                'name' => 'equipment/maintenance',
                'title' => '保养计划',
                'icon' => 'fa fa-clock-o',
                'condition' => '',
                'remark' => '',
                'ismenu' => 1,
                'sublist' => [
                    [
                        'type' => 'file',
                        'name' => 'equipment/maintenance/index',
                        'title' => '查看',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/maintenance/add',
                        'title' => '添加',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/maintenance/deactivated',
                        'title' => '已停用计划',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                ],
            ],
            [
                'type' => 'file',
                'name' => 'equipment/plan',
                'title' => '设备计划',
                'icon' => 'fa fa-recycle',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'sublist' => [
                    [
                        'type' => 'file',
                        'name' => 'equipment/plan/stop',
                        'title' => '计划停用',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/plan/list',
                        'title' => '设备明细',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/plan/clearInvalidTask',
                        'title' => '清理无效任务',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/plan_field/fields',
                        'title' => '检查项',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                ],
            ],
            [
                'type' => 'file',
                'name' => 'equipment/record',
                'title' => '设备记录',
                'icon' => 'fa fa-list-alt',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'sublist' => [
                    [
                        'type' => 'file',
                        'name' => 'equipment/record/list',
                        'title' => '记录明细',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/record/detail',
                        'title' => '记录详情',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                ],
            ],
            [
                'type' => 'file',
                'name' => 'equipment/repair',
                'title' => '维修工单',
                'icon' => 'fa fa-wrench',
                'condition' => '',
                'remark' => '',
                'ismenu' => 1,
                'sublist' => [
                    [
                        'type' => 'file',
                        'name' => 'equipment/repair/index',
                        'title' => '查看',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/repair/detail',
                        'title' => '详情',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/repair/assignment',
                        'title' => '指派',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/repair/register',
                        'title' => '登记',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/repair/edit',
                        'title' => '编辑',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/repair/add',
                        'title' => '添加',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/repair/del',
                        'title' => '删除',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/repair/multi',
                        'title' => '批量更新',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                ],
            ],
            [
                'type' => 'file',
                'name' => 'equipment/failure_cause',
                'title' => '故障原因',
                'icon' => 'fa fa-bug',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'sublist' => [
                    [
                        'type' => 'file',
                        'name' => 'equipment/failure_cause/index',
                        'title' => '查看',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/failure_cause/edit',
                        'title' => '编辑',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/failure_cause/add',
                        'title' => '添加',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/failure_cause/del',
                        'title' => '删除',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/failure_cause/multi',
                        'title' => '批量更新',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/failure_cause/recyclebin',
                        'title' => '回收站',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/failure_cause/restore',
                        'title' => '回收站-还原',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/failure_cause/destroy',
                        'title' => '回收站-销毁',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                ],
            ],
            [
                'type' => 'file',
                'name' => 'equipment/reminder_users',
                'title' => '提醒人员',
                'icon' => 'fa fa-bullhorn',
                'condition' => '',
                'remark' => '',
                'ismenu' => 0,
                'sublist' => [
                    [
                        'type' => 'file',
                        'name' => 'equipment/reminder_users/index',
                        'title' => '查看',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/reminder_users/add',
                        'title' => '添加',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/reminder_users/del',
                        'title' => '删除',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'equipment/reminder_users/multi',
                        'title' => '批量更新',
                        'icon' => 'fa fa-circle-o',
                        'condition' => '',
                        'remark' => '',
                        'ismenu' => 0,
                    ],
                ],
            ],
        ],
    ],
];