<?php
/**
 * 菜单配置文件
 */

return array (
  0 => 
  array (
    'type' => 'file',
    'name' => 'screen',
    'title' => '可视化大屏管理',
    'icon' => 'fa fa-cc-discover',
    'url' => '',
    'condition' => '',
    'remark' => '',
    'ismenu' => 1,
    'menutype' => 'addtabs',
    'extend' => '',
    'py' => 'kshdpgl',
    'pinyin' => 'keshihuadapingguanli',
    'weigh' => 0,
    'sublist' => 
    array (
      0 => 
      array (
        'type' => 'file',
        'name' => 'screen/page',
        'title' => '大屏管理',
        'icon' => 'fa fa-tachometer',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'menutype' => 'addtabs',
        'extend' => '',
        'py' => 'dpgl',
        'pinyin' => 'dapingguanli',
        'weigh' => 99,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'screen/page/index',
            'title' => '查看',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'zk',
            'pinyin' => 'zhakan',
            'weigh' => 0,
          ),
          1 => 
          array (
            'type' => 'file',
            'name' => 'screen/page/recyclebin',
            'title' => '回收站',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'hsz',
            'pinyin' => 'huishouzhan',
            'weigh' => 0,
          ),
          2 => 
          array (
            'type' => 'file',
            'name' => 'screen/page/add',
            'title' => '添加',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'tj',
            'pinyin' => 'tianjia',
            'weigh' => 0,
          ),
          3 => 
          array (
            'type' => 'file',
            'name' => 'screen/page/edit',
            'title' => '编辑',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'bj',
            'pinyin' => 'bianji',
            'weigh' => 0,
          ),
          4 => 
          array (
            'type' => 'file',
            'name' => 'screen/page/del',
            'title' => '删除',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'sc',
            'pinyin' => 'shanchu',
            'weigh' => 0,
          ),
          5 => 
          array (
            'type' => 'file',
            'name' => 'screen/page/destroy',
            'title' => '真实删除',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'zssc',
            'pinyin' => 'zhenshishanchu',
            'weigh' => 0,
          ),
          6 => 
          array (
            'type' => 'file',
            'name' => 'screen/page/restore',
            'title' => '还原',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'hy',
            'pinyin' => 'huanyuan',
            'weigh' => 0,
          ),
          7 => 
          array (
            'type' => 'file',
            'name' => 'screen/page/multi',
            'title' => '批量更新',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'plgx',
            'pinyin' => 'pilianggengxin',
            'weigh' => 0,
          ),
          8 => 
          array (
            'type' => 'file',
            'name' => 'screen/page/export',
            'title' => '导出',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'dc',
            'pinyin' => 'daochu',
            'weigh' => 0,
          ),
          9 => 
          array (
            'type' => 'file',
            'name' => 'screen/page/import',
            'title' => '导入',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'dr',
            'pinyin' => 'daoru',
            'weigh' => 0,
          ),
        ),
      ),
      1 => 
      array (
        'type' => 'file',
        'name' => 'screen/data',
        'title' => '数据集',
        'icon' => 'fa fa-database',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'menutype' => 'addtabs',
        'extend' => '',
        'py' => 'sjj',
        'pinyin' => 'shujuji',
        'weigh' => 0,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'screen/data/index',
            'title' => '查看',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'zk',
            'pinyin' => 'zhakan',
            'weigh' => 0,
          ),
          1 => 
          array (
            'type' => 'file',
            'name' => 'screen/data/recyclebin',
            'title' => '回收站',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'hsz',
            'pinyin' => 'huishouzhan',
            'weigh' => 0,
          ),
          2 => 
          array (
            'type' => 'file',
            'name' => 'screen/data/add',
            'title' => '添加',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'tj',
            'pinyin' => 'tianjia',
            'weigh' => 0,
          ),
          3 => 
          array (
            'type' => 'file',
            'name' => 'screen/data/edit',
            'title' => '编辑',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => 'addtabs',
            'extend' => '',
            'py' => 'bj',
            'pinyin' => 'bianji',
            'weigh' => 0,
          ),
          4 => 
          array (
            'type' => 'file',
            'name' => 'screen/data/del',
            'title' => '删除',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'sc',
            'pinyin' => 'shanchu',
            'weigh' => 0,
          ),
          5 => 
          array (
            'type' => 'file',
            'name' => 'screen/data/destroy',
            'title' => '真实删除',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'zssc',
            'pinyin' => 'zhenshishanchu',
            'weigh' => 0,
          ),
          6 => 
          array (
            'type' => 'file',
            'name' => 'screen/data/restore',
            'title' => '还原',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'hy',
            'pinyin' => 'huanyuan',
            'weigh' => 0,
          ),
          7 => 
          array (
            'type' => 'file',
            'name' => 'screen/data/multi',
            'title' => '批量更新',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'plgx',
            'pinyin' => 'pilianggengxin',
            'weigh' => 0,
          ),
        ),
      ),
      2 => 
      array (
        'type' => 'file',
        'name' => 'screen/share',
        'title' => '分享记录',
        'icon' => 'fa fa-share-alt',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'menutype' => 'addtabs',
        'extend' => '',
        'py' => 'fxjl',
        'pinyin' => 'fenxiangjilu',
        'weigh' => -1,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'screen/share/index',
            'title' => '查看',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'zk',
            'pinyin' => 'zhakan',
            'weigh' => 0,
          ),
          1 => 
          array (
            'type' => 'file',
            'name' => 'screen/share/recyclebin',
            'title' => '回收站',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'hsz',
            'pinyin' => 'huishouzhan',
            'weigh' => 0,
          ),
          2 => 
          array (
            'type' => 'file',
            'name' => 'screen/share/add',
            'title' => '添加',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'tj',
            'pinyin' => 'tianjia',
            'weigh' => 0,
          ),
          3 => 
          array (
            'type' => 'file',
            'name' => 'screen/share/edit',
            'title' => '编辑',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'bj',
            'pinyin' => 'bianji',
            'weigh' => 0,
          ),
          4 => 
          array (
            'type' => 'file',
            'name' => 'screen/share/del',
            'title' => '删除',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'sc',
            'pinyin' => 'shanchu',
            'weigh' => 0,
          ),
          5 => 
          array (
            'type' => 'file',
            'name' => 'screen/share/destroy',
            'title' => '真实删除',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'zssc',
            'pinyin' => 'zhenshishanchu',
            'weigh' => 0,
          ),
          6 => 
          array (
            'type' => 'file',
            'name' => 'screen/share/restore',
            'title' => '还原',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'hy',
            'pinyin' => 'huanyuan',
            'weigh' => 0,
          ),
          7 => 
          array (
            'type' => 'file',
            'name' => 'screen/share/multi',
            'title' => '批量更新',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'plgx',
            'pinyin' => 'pilianggengxin',
            'weigh' => 0,
          ),
        ),
      ),
      3 => 
      array (
        'type' => 'file',
        'name' => 'screen/excel',
        'title' => 'Excel报表',
        'icon' => 'fa fa-table',
        'url' => '',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'menutype' => 'addtabs',
        'extend' => '',
        'py' => 'Ebb',
        'pinyin' => 'Excelbaobiao',
        'weigh' => 97,
        'sublist' => 
        array (
          0 => 
          array (
            'type' => 'file',
            'name' => 'screen/excel/index',
            'title' => '查看',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'zk',
            'pinyin' => 'zhakan',
            'weigh' => 0,
          ),
          1 => 
          array (
            'type' => 'file',
            'name' => 'screen/excel/recyclebin',
            'title' => '回收站',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'hsz',
            'pinyin' => 'huishouzhan',
            'weigh' => 0,
          ),
          2 => 
          array (
            'type' => 'file',
            'name' => 'screen/excel/add',
            'title' => '添加',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'tj',
            'pinyin' => 'tianjia',
            'weigh' => 0,
          ),
          3 => 
          array (
            'type' => 'file',
            'name' => 'screen/excel/edit',
            'title' => '编辑',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'bj',
            'pinyin' => 'bianji',
            'weigh' => 0,
          ),
          4 => 
          array (
            'type' => 'file',
            'name' => 'screen/excel/del',
            'title' => '删除',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'sc',
            'pinyin' => 'shanchu',
            'weigh' => 0,
          ),
          5 => 
          array (
            'type' => 'file',
            'name' => 'screen/excel/destroy',
            'title' => '真实删除',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'zssc',
            'pinyin' => 'zhenshishanchu',
            'weigh' => 0,
          ),
          6 => 
          array (
            'type' => 'file',
            'name' => 'screen/excel/restore',
            'title' => '还原',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'hy',
            'pinyin' => 'huanyuan',
            'weigh' => 0,
          ),
          7 => 
          array (
            'type' => 'file',
            'name' => 'screen/excel/multi',
            'title' => '批量更新',
            'icon' => 'fa fa-circle-o',
            'url' => '',
            'condition' => '',
            'remark' => '',
            'ismenu' => 0,
            'menutype' => NULL,
            'extend' => '',
            'py' => 'plgx',
            'pinyin' => 'pilianggengxin',
            'weigh' => 0,
          ),
        ),
      ),
    ),
  ),
);