<?php

return [
    [
        'name' => 'platform',
        'title' => '所有平台',
        'type' => 'checkbox',
        'content' => [
            'user' => '用户',
            'admin' => '后台',
        ],
        'value' => 'user,admin',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'type',
        'title' => '所有类型',
        'type' => 'checkbox',
        'content' => [
            'msg' => '站内消息',
            'email' => '邮件通知',
            'mptemplate' => '模版消息(公众号)',
            'miniapp' => '小程序订阅消息',
            'sms' => '短信通知'
        ],
        'value' => 'msg,email,mptemplate,miniapp,sms',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'open',
        'title' => '平台支持类型',
        'type' => 'array',
        'content' => [],
        'value' => [
            'user' => 'msg,email,mptemplate,miniapp,sms',
            'admin' => 'msg,email,mptemplate,miniapp,sms',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'only_admin_group_id',
        'title' => '全局指定角色管理员获取消息',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '不填写为全部分组管理员可以获取，输入例如 1,2 表示角色id=1,2的管理员才可以获取消息。',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'auto_read',
        'title' => '站内消息自动阅读',
        'type' => 'bool',
        'content' => [],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'app_id',
        'title' => '公众号appid',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '如果为空从登录插件/支付插件里面获取',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'secret',
        'title' => '公众号secret',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '如果为空从登录插件/支付插件里面获取',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'mini_app_id',
        'title' => '小程序appid',
        'type' => 'string',
        'content' => [],
        'value' => 'wxcadd50d6a504****',
        'rule' => '',
        'msg' => '',
        'tip' => '选填，需要小程序订阅消息的时候需要配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'mini_secret',
        'title' => '小程序secret',
        'type' => 'string',
        'content' => [],
        'value' => 'eeca72425aaff31204e76118690*****',
        'rule' => '',
        'msg' => '',
        'tip' => '选填，需要小程序订阅消息的时候需要配置',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'admin_real',
        'title' => '后台实时获取站内消息',
        'type' => 'select',
        'content' => [
            '关闭',
            'ajax轮询',
            'websocket',
        ],
        'value' => '1',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'user_real',
        'title' => '前台实时获取站内消息',
        'type' => 'select',
        'content' => [
            '关闭',
            'ajax轮询',
            'websocket',
        ],
        'value' => '0',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'user_real_url',
        'title' => '前台实时获取站内消息的url',
        'type' => 'array',
        'content' => [
            '*',
        ],
        'value' => [
            '*',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
        'visible' => 'user_real=2||user_real=1',
    ],
    [
        'name' => 'websocket_port',
        'title' => 'WebSocket端口',
        'type' => 'string',
        'content' => [],
        'value' => '6006',
        'rule' => '',
        'msg' => '',
        'tip' => '请在安全组、防火墙等开放此端口',
        'ok' => '',
        'extend' => '',
        'visible' => 'user_real=2||admin_real=2',
    ],
    [
        'name' => 'register_port',
        'title' => '服务注册端口',
        'type' => 'string',
        'content' => [],
        'value' => '6206',
        'rule' => '',
        'msg' => '',
        'tip' => '无需对外开放,属未被占用的端口即可',
        'ok' => '',
        'extend' => '',
        'visible' => 'user_real=2||admin_real=2',
    ],
    [
        'name' => 'internal_start_port',
        'title' => '内部通讯起始端口',
        'type' => 'string',
        'content' => [],
        'value' => '6406',
        'rule' => '',
        'msg' => '',
        'tip' => '无需对外开放,属未被占用的端口即可',
        'ok' => '',
        'extend' => '',
        'visible' => 'user_real=2||admin_real=2',
    ],
    [
        'name' => 'wss_switch',
        'title' => 'wss协议',
        'type' => 'radio',
        'content' => [
            '不开启',
            '开启',
        ],
        'value' => '0',
        'rule' => '',
        'tip' => '请先参考常见问题配置好wss服务再开启，否则将无法链接',
        'ok' => '',
        'extend' => '',
        'visible' => 'user_real=2||admin_real=2',
    ],
    [
        'name' => 'ssl_cert',
        'title' => 'ssl证书',
        'type' => 'string',
        'content' => [],
        'value' => '/www/wwwroot/a.cn/cert/a.cn.pem',
        'rule' => '',
        'tip' => '请填写证书pem或crt文件的绝对路径',
        'ok' => '',
        'extend' => '',
        'visible' => 'user_real=2||admin_real=2',
    ],
    [
        'name' => 'ssl_cert_key',
        'title' => 'ssl证书KEY',
        'type' => 'string',
        'content' => [],
        'value' => '/www/wwwroot/a.cn/cert/a.cn.key',
        'rule' => '',
        'tip' => '请填写证书密匙(key)文件的绝对路径',
        'ok' => '',
        'extend' => '',
        'visible' => 'user_real=2||admin_real=2',
    ],
    [
        'name' => 'is_test_miniapp_template',
        'title' => '是否开启微信订阅消息测试模式',
        'type' => 'radio',
        'content' => [
            '不开启',
            '开启',
        ],
        'value' => '0',
        'rule' => '',
        'tip' => '只有测试微信订阅消息的时候才打开，其它场景请关闭。',
        'ok' => '',
        'extend' => '',
        'visible' => '',
    ],
];
